requirements/test.txt

Using edx-lint from PyPI

---

programs/apps/api/models.py
programs/apps/api/serializers.py
programs/apps/api/v1/tests/test_views.py
programs/apps/api/v1/urls.py
programs/apps/api/v1/views.py
programs/apps/programs/constants.py
programs/apps/programs/migrations/0001_initial.py
programs/apps/programs/models.py
programs/apps/programs/tests/factories.py
programs/settings/base.py
requirements/test.txt

ECOM-2186
@clintonb @rlucioni  I'm working on the authentication / roles part of the ACs next, but ready for feedback on what's implemented so far.

WIP: Initial Program creation / list views.

---

.gitignore
.jscsrc
.jshintrc
.travis.yml
Makefile
bower.json
build.js
gulpfile.js
karma.conf.js
package.json
programs/conf/locale/config.yaml
programs/settings/base.py
programs/settings/production.py
programs/settings/test.py
programs/static/js/common.js
programs/static/js/config.js
programs/static/js/test/spec-runner.js
programs/static/js/test/specs/example_spec.js
programs/static/sass/main.scss
programs/templates/base.html
requirements/base.txt
requirements/production.txt

Added support for static assets

---

README.rst

Replaced Coveralls badge with Codecov badge

---

programs/static/js/apps/program_admin_app.js
programs/static/js/collections/programs_collection.js
programs/static/js/models/pagination_model.js
programs/static/js/models/program_model.js
programs/static/js/views/program_list_view.js
programs/static/templates/program_list.underscore
programs/templates/author.html

Added template rendering and app is now hooking into the DOM
Now hitting actual API
@rlucioni @jimabramson please review.
Note that pagination has not been plugged in yet - I propose making this its own ticket.

ECOM-2414 added a simple 'app'

---

programs/apps/programs/admin.py
programs/apps/programs/migrations/0003_auto_20151022_1836.py
programs/apps/programs/models.py

Also fix uniqueness constraint on ProgramCourseCode. This started more restrictive than it is now. I've intentionally exposed a lot in the admin to give us flexibility as we get this service established. ECOM-2626.
@jimabramson @edx/ecommerce

Expose all programs models in the Django admin.

---

programs/urls.py

Allow the Programs authoring app to handle its own routing

---

programs/apps/api/serializers.py
programs/apps/api/v1/tests/test_views.py
programs/apps/programs/admin.py
programs/apps/programs/migrations/0003_program_marketing_slug.py
programs/apps/programs/models.py
programs/apps/programs/tests/factories.py
programs/apps/programs/tests/test_models.py

Add marketing_slug to Program

---

requirements/optional.txt

Be able to install new-relic optionally for programs.

---

programs/settings/production.py
programs/settings/utils.py

Define production logging configuration

---

README.rst
docs/index.rst
docs/programs.rst

I noticed that the Programs README was never updated. I've taken the liberty of updating it and uploading the docs to RTD.
@jimabramson @edx/ecommerce

Update programs README

---

bower.json
programs/static/js/config.js
programs/static/js/models/program_model.js
programs/static/js/test/spec-runner.js
programs/static/js/test/specs/program_creator_spec.js
programs/static/js/views/program_creator_view.js
programs/static/templates/program_creator_form.underscore

The ProgramCreatorView won't save its model unless all validation rules are followed. ECOM-2711.
@AlasdairSwan and @jimabramson, could you please review this?

Add validation to the Backbone Program model and creation view

---

requirements/base.txt

[Release notes](https://docs.djangoproject.com/en/1.8/releases/1.8.6/)
@edx/ecommerce

Upgrade Django to 1.8.6.

---

programs/static/js/models/program_model.js
programs/static/js/test/specs/program_creator_spec.js
programs/static/js/views/program_creator_view.js
programs/static/templates/program_creator_form.underscore

Added tests and validation
@rlucioni @jimabramson please review

added marketing slug field to form

---

CONTRIBUTORS.txt
programs/apps/api/parsers.py
programs/apps/api/v1/tests/test_views.py
programs/apps/api/v1/views.py

ECOM-2752
* Update Program API to accept patch requests.
* Write Program test to check update program attributes using patch.
@awais786 @zubair-arbi @tasawernawaz @afeef please review.

Update program attributes

---

programs/apps/api/authentication.py
programs/apps/api/tests/test_authentication.py

Django's get_or_create is vulnerable to a race condition which can cause user creation to fail. Retrying when failures occur should cause the object responsible for the initial failure to be retrieved. ECOM-2840.
@jimabramson please review.

Make JWT authentication handler more robust

---

build.js

Build the Programs authoring app when compiling static assets

---

programs/apps/api/v1/tests/test_views.py

ECOM-2752.
@jimabramson, please review. @AlasdairSwan, FYI. This will require the authoring app to submit data only for fields being modified. For example, if the subtitle is changed from "foo" to "bar," the API will expect a PATCH request with the following payload:
```javascript
{'subtitle': 'bar'}
```

Support updating programs via PATCH requests

---

programs/static/js/models/program_model.js
programs/static/js/test/specs/program_details_spec.js
programs/static/js/views/program_details_view.js

@rlucioni @jimabramson here is the update to make it so that PATCH only sends the changed data. Thus involved less code than I first thought.

Updating data for a push

---

requirements/base.txt

Upgraded to Django 1.8.7

---

build.js
programs/static/js/models/program_model.js

Also initialize program model with a CORS-friendly URL (no redirection required).
@jimabramson this will help fix the issues we were seeing earlier. @AlasdairSwan FYI.

Allow restructured authoring app to be bundled

---

programs/apps/programs/migrations/0005_auto_20151204_2212.py
programs/apps/programs/models.py

Increase max length of Program.name field.

---

programs/static/js/models/api_config_model.js
programs/static/js/models/auto_auth_model.js
programs/static/js/models/organizations_model.js
programs/static/js/models/pagination_model.js
programs/static/js/models/program_model.js
programs/static/js/test/specs/auto_auth_model_spec.js
programs/static/js/test/specs/program_creator_spec.js
programs/static/js/views/program_admin_app_view_core.js
programs/static/js/views/program_admin_app_view_dev.js
programs/templates/program.html

ECOM-3034.
@AlasdairSwan, please review. @jimabramson, FYI.

Set API base and auth URLs from data attributes.

---

programs/apps/api/serializers.py
programs/apps/api/v1/tests/test_views.py

@AlasdairSwan @rlucioni FYI.
This is based on top of #62.  I'm going to return to that one now, but want to get this one on your radar, particularly because it may be useful to unblocking JS work that depends on it.

During program updates, create/update course codes on the fly.

---

programs/apps/api/serializers.py
programs/apps/api/v1/tests/test_views.py

Inadvertently omitted from 6163139ffc32887cb9bfea241c7f917ca7c986c2
@rlucioni FYI, found the missing changes.  Not related to test failures being discussed elsewhere.

Trivial quality fixes.

---

programs/static/js/models/course_model.js
programs/static/js/test/specs/program_details_spec.js
programs/static/js/views/course_details_view.js
programs/static/templates/course_details.underscore

@rlucioni @jimabramson please review. Not that once the APIs and all of the other  sub-tasks have been completed the tests will be more fully updated so increase coverage.

ECOM 2764 course data input fields

---

programs/apps/api/v1/views.py

Prevents serialized nested relationships from incurring n+1 round-trips to the database. ECOM-3173.
@jimabramson please review. I've not yet been able to figure out the test failures. The Django debug toolbar indicates that prefetching cuts the number of queries made on GETs to /api/v1/programs/ by about 70% (e.g., with 6 programs, 3 orgs, 5 course codes, and 9 course run modes, the query count drops from 39 to 12).

Eagerly load serialized data to prevent cascades of performance-degrading queries

---

programs/settings/base.py
programs/static/js/models/auto_auth_model.js

Allow CORS requests to be made using authorization headers

---

Makefile
build.js
programs/settings/base.py

Yields minified files with unhashed names we can use to fetch these assets from Studio. ECOM-2862.
@AlasdairSwan please review. @jimabramson FYI.

Use RequireJS Optimizer to minify JS and CSS

---

docs/getting_started.rst

Document significance and creation of trusted clients

---

programs/static/js/models/api_config_model.js
programs/static/js/models/organizations_model.js
programs/static/js/models/pagination_model.js
programs/static/js/models/program_model.js
programs/static/js/views/program_admin_app_view_core.js
programs/static/js/views/program_admin_app_view_dev.js
programs/templates/program.html

@rlucioni the changes needed in light of https://github.com/edx/edx-platform/pull/11101

ECOM-3047 updated to use programs api url instead of programs base url

---

karma.conf.js
programs/static/js/shims/edx-icons.js
programs/static/sass/_font-files.scss
programs/static/sass/_scoped-pattern-library.scss
programs/static/sass/_uxpl-icons.scss
programs/static/sass/_uxpl-variables-sans-fonts.scss
programs/static/sass/fonts.scss
programs/templates/base.html
programs/templates/program.html

Assumption is being made that other apps using the programs IDA will already have loaded OpenSans and edx-icons fonts
@jimabramson @rlucioni please review
**NB** there will be an accompanying PR to add the font file to studio.

ECOM-3319 updated so only loading font files in local app.

---

programs/static/js/collections/course_runs_collection.js
programs/static/js/models/api_config_model.js
programs/static/js/views/program_admin_app_view_core.js
programs/static/js/views/program_admin_app_view_dev.js
programs/templates/program.html

@rlucioni @AlasdairSwan FYI.
Also fixes the query string for org filtering.

get username from DOM, fixing course API requests.

---

programs/static/js/models/organizations_model.js

@AlasdairSwan note this is a simpler fix than you had suggested but it seems to work out.  LMK what you think.

wait to set organization model urlRoot until init

---

programs/apps/core/migrations/0002_add_credentials_service_user.py
programs/settings/base.py

ECOM-3382
@zubair-arbi @awais786 @tasawernawaz

Add service user for credentials

---

programs/static/js/views/course_details_view.js

substitute _.findIndex to fix course run selection

---

programs/static/js/models/organizations_model.js

@AlasdairSwan here's a quickie

Ensure all orgs are loaded into the dropdown.

---

programs/static/js/models/course_model.js
programs/static/js/utils/validation_config.js
programs/static/sass/_app-typography.scss
programs/static/sass/_components.scss
programs/static/sass/_modals.scss
programs/static/templates/course_details.underscore
programs/static/templates/course_run.underscore
programs/static/templates/program_creator_form.underscore
programs/static/templates/program_details.underscore

ECOM-3403 UI tweaks ahoy

---

programs/apps/api/v1/views.py

@AlasdairSwan makes the org dropdown easier to use - the order was previously arbitrary

Order orgs by key in dropdown

---

programs/static/js/views/course_run_view.js

@AlasdairSwan fixes problems with course runs that don't have any SKU

don’t complain about empty sku in course run mode

---

programs/apps/api/v1/tests/test_views.py
programs/apps/api/v1/views.py
programs/urls.py

The endpoint currently returns all program IDs, but will be refined soon. ECOM-3352.
@jimabramson

Add interface for program completion endpoint

---

programs/static/js/test/specs/program_details_spec.js

Clean up following https://github.com/edx/programs/pull/93. @jimabramson FYI.

Remove unnecessary variable from JS unit test

---

programs/apps/api/filters.py
programs/apps/api/v1/tests/test_views.py
programs/apps/api/v1/views.py
programs/apps/programs/tests/test_utils.py
programs/apps/programs/utils.py

Completes the program completion endpoint. ECOM-3353.
@jimabramson please review.

Implement program completion logic

---

requirements/base.txt

@rlucioni @AlasdairSwan @clintonb @zubair-arbi FYI

pin libsass to 0.10.0, to unbreak `compress`

---

programs/static/js/collections/course_runs_collection.js
programs/static/js/test/specs/program_details_spec.js
programs/static/js/views/course_run_view.js
programs/static/js/views/program_details_view.js
programs/static/templates/course_run.underscore

Change being made due to https://github.com/edx/edx-platform/pull/11077.
@AlasdairSwan please review when able. @nasthagiri FYI.

Use Course API's id field instead of the deprecated course_id

---

programs/apps/programs/management/commands/sync_orgs.py
programs/apps/programs/tests/test_sync_orgs.py

The access token is used to make authenticated requests against the LMS Organizations API. ECOM-3349.
@jimabramson please review. @schenedx, how do you feel about reviewing this, too? I'm not sure if you've reviewed anything in the programs project before.

Allow org sync management command to accept an access token

---

programs/static/templates/course_run.underscore

ECOM-3635
@AlasdairSwan @schenedx FYI.

Display course modes in authoring tool.

---

programs/apps/programs/tests/test_utils.py

ECOM-3635
@rlucioni @schenedx please review.

Harden test coverage for programs with mixed course modes.

---

requirements/monitoring/requirements.txt

Added requirements monitoring file

---

requirements/base.txt

Upgrade Django to 1.8.10

---

Makefile
acceptance_tests/config.py
acceptance_tests/mixins.py
acceptance_tests/pages.py
acceptance_tests/test_programs.py
docs/testing.rst
programs/apps/api/v1/tests/test_views.py
requirements/test.txt

@jimabramson @rlucioni I want you guys to start review this work while I work on documentation and incorporate these into build.
I believe this PR is ready for full review and merge for it's current state.
As for leverage the acceptance tests for build process, that's now a separate story at ECOM-3822

ECOM-3123 Acceptance test for Programs authoring app in Studio

---

acceptance_tests/requirements.txt
requirements/monitoring/requirements.txt

Counterpart to https://github.com/edx/ecommerce/pull/634 and https://github.com/edx-ops/edx-jenkins-job-dsl/pull/16. @schenedx @benpatterson

Add separate requirements file for acceptance testing

---

.gitignore
programs/apps/api/serializers.py
programs/apps/api/v1/tests/test_views.py
programs/apps/core/s3utils.py
programs/apps/core/tests/test_s3utils.py
programs/apps/programs/admin.py
programs/apps/programs/fields.py
programs/apps/programs/image_helpers.py
programs/apps/programs/migrations/0007_auto_20160318_1859.py
programs/apps/programs/models.py
programs/apps/programs/tests/helpers.py
programs/apps/programs/tests/test_fields.py
programs/apps/programs/tests/test_image_helpers.py
programs/settings/production.py
programs/urls.py
requirements/base.txt

Add support for program banner images

---

requirements/base.txt

update to django 1.8.11

---

programs/apps/api/serializers.py
programs/apps/api/v1/tests/test_views.py

@schenedx @AlasdairSwan pls review.

Fix banner image url keys in programs API response

---

requirements/base.txt

Upgrade auth-backends to 0.2.3

---

programs/apps/api/v1/views.py

No longer necessary after work done in https://github.com/edx/edx-platform/pull/12700.
@schenedx @mikedikan FYI.

Add deprecation warning to completion endpoint

---

package.json

For more details, see https://github.com/react-toolbox/react-toolbox/issues/468.
@mikedikan this fixes the issue blocking us earlier today.

Fix CSS compilation

---

programs/apps/api/serializers.py
programs/apps/api/v1/tests/test_views.py

Exposing program UUID field

---

requirements/base.txt

Upgrade to Django 1.8.14

---

docs/conf.py

Set the copyright year in docs dynamically

---

.travis.yml
Makefile
requirements/local.txt

Updated i18n-tool version, .travis.yml and Makefile files changed

---

requirements/optional.txt

ECOM-6313
@rlucioni for review
FYI @edx/ecommerce

Update New Relic Agent to avoid bug

---

.travis.yml
.travis/docker-compose-travis.yml

Move the travis related docker-compose file to the .travis folder.

---

requirements/base.txt

updated pillow
