edx/programs

programs/apps/api/v1/views.py, programs/settings/base.py, programs/urls.py, requirements/base.txt
@clintonb @peter-fogg @bderusha @rlucioni 
establishing api documentation, following the guideline: https://openedx.atlassian.net/wiki/display/AC/edX+REST+API+Conventions#edXRESTAPIConventions-8.Documentation
The swagger output looks nice, though it's not perfect.
The inability to create separate documentation sections for each method in a viewset is troublesome, wonder if anyone knows a workaround that doesn't involve restructuring code.
=> WIP API documentation

programs/templates/author.html, programs/urls.py
Only for development and testing of the API client. ECOM-2591. @edx/ecommerce 
@AlasdairSwan, FYI. I've left you a placeholder script tag which you can use to load the client, once available.
=> Serve a page which loads the JS API client

docs/getting_started.rst, programs/apps/programs/fixtures/sample_data.json, programs/apps/programs/tests/test_fixtures.py
This fixture can be used to pre-populate the database with sample data when setting up the service for development or load testing. The fixture sets up two organizations with a program apiece. Each program contains two course codes, and each course code contains two runs. ECOM-2712.
@jimabramson @edx/ecommerce
=> Provide sample data via a fixture

programs/settings/production.py
Without this, the base JWT settings are used and the configured credentials are never pulled in. ECOM-2627.
@jimabramson @feanil
=> Update JWT settings when running in a production environment

CONTRIBUTORS.txt, programs/apps/api/serializers.py, programs/apps/api/v1/tests/test_views.py, programs/apps/programs/admin.py, programs/apps/programs/fixtures/sample_data.json, programs/apps/programs/migrations/0004_start_date_run_key.py, programs/apps/programs/models.py, programs/apps/programs/tests/factories.py, programs/apps/programs/tests/test_models.py, requirements/base.txt
[ECOM-2637](https://openedx.atlassian.net/browse/ECOM-2637)
* Added two new fields in ProgramCourseRunMode model. Field names are as follows
* **start_date**
* **run_key**
* New Json look like
```javascript
"run_modes": [
{
"course_key": "edX/DemoX/Demo_Course",
"mode_slug": "edxslug",
"sku": "111",
"start_date": "2015-11-04T08:46:47Z",
"run_key": "abc"
}
]
```
* Update the ProgramCourseRunModeFactory 
* Update the test case to reflect the new json changes.
* Add the opaque key in this repo.
* Parse the run_key from course_key in save method.
=> Adding the new fields in model , update the test cases accordingly.

programs/apps/api/authentication.py, programs/apps/api/exception_handler.py, programs/apps/api/tests/test_exception_handler.py, programs/settings/base.py, requirements/test.txt
The hope is that this will shed light on the cause of sporadic 401 errors.
ECOM-2839
@rlucioni  please review.
=> Log details when 401 responses are returned.

programs/apps/api/jwt_decode_handler.py, programs/apps/api/tests/test_authentication.py, programs/apps/api/v1/tests/mixins.py, programs/settings/base.py
ECOM-2839
Process of elimination points to the "iat" (issued at) claim in programs JWT tokens as the cause of intermittent bursts of 401 errors.  This is the only claim with a dynamic value present in these tokens that is not present in ecom tokens (which do not experience such errors).  It's a timestamp on the generation of the JWT.   If the clock on a host where the JWT is generated is even a fraction of a second ahead of the clock on the host where it's read, the JWT can appear to have been generated in the future, and thus be considered invalid.
"Leeway" is a setting which allows the JWT library to tolerate drift between clocks on two systems - this PR changes it from the library default (zero tolerance) to 1 second.
Also in this PR are changes to require the presence of "exp" and …
=> adjust JWT_LEEWAY and use custom JWT decode function

programs/apps/api/serializers.py, programs/apps/api/v1/tests/test_views.py, programs/apps/api/v1/views.py
ECOM-2727
@ahsan-ul-haq @awais786 @afeef @tasawernawaz 
Save Program with provided valid `Organization` (with its `key`) or raise validation errors.
* POST request for endpoint `/programs/` expects a nested array containing exactly one object in the `'organizations'` field, and it contains a 'key' which references an org known to the system.
* POST request for endpoint `/programs/` returns a 400, if:
* the `key` does not match the key of an organization in the db
* the length of the array `'organizations'` is anything other than 1
=> Save ProgramOrganization with Program in creation endpoint

requirements/test.txt
~~Fixes new quality violations flagged by pylint, including several false positives. :unamused:~~
Required by pylint. astroid 1.4.1 and pylint 1.5.0 both have bugs preventing quality checks from completing.
@peter-fogg or @clintonb, please review. @AlasdairSwan @jimabramson FYI. This blocks builds for https://github.com/edx/programs/pull/50, https://github.com/edx/programs/pull/51, https://github.com/edx/programs/pull/52, and https://github.com/edx/programs/pull/53.
=> Pin astroid to 1.3.8

build.js
Fixes post-build issues when using an AMD-aware version of Backbone, but using shim config for scripts that depend on Backbone (e.g., Backbone.Validation). ECOM-2598.
@AlasdairSwan please review. @jimabramson FYI.
=> Use r.js' wrapShim option

programs/settings/base.py, programs/static/js/models/program_model.js, requirements/base.txt
The Programs API must allow CORS in order for the authoring app to function in Studio. ECOM-2598.
@jimabramson please review. @AlasdairSwan FYI.
=> Set up Programs API for CORS

programs/static/js/models/api_config_model.js, programs/static/js/models/auto_auth_model.js, programs/static/js/models/course_list_model.js, programs/static/js/models/organizations_model.js, programs/static/js/models/pagination_model.js, programs/static/js/models/program_model.js, programs/static/js/test/specs/auto_auth_model_spec.js, programs/static/js/utils/api_config.js
ECOM-2440
Changed direction here, to avoid nasty issues with CORS and CSRF.  Now, we use a dedicated endpoint to request an id token for API requests whenever we need one, and save its value in a new model in the client app.
Depends on a new endpoint in Studio, which merged in https://github.com/edx/edx-platform/pull/10862.  Note that this works fine when the app is embedded studio; using the development version currently requires modifying Studio to whitelist the id_token endpoint with CORS. 
@rlucioni @AlasdairSwan please review.
=> Automatically authenticate client using id token endpoint.

programs/apps/api/serializers.py, programs/apps/api/v1/tests/test_views.py, programs/apps/programs/models.py, programs/apps/programs/tests/factories.py
ECOM-2210
This allows program course codes and run modes to be updated as part of a Programs PATCH request.
Note that this does not support creating program course codes based on course codes not yet known to the system.  This PR was getting big, so I plan to address that in a second, separate PR.
@rlucioni  I'm aware of a coverage gap that needs to be closed, but this is otherwise ready for review.
=> Allow nested writes during Program updates.

programs/static/js/test/specs/program_creator_spec.js, programs/static/js/views/program_creator_view.js
Formerly redirected to '/program/program/:id'. Now redirects to '/program/:id'. ECOM-3120.
@AlasdairSwan please review. @jimabramson FYI.
=> Fix incorrect routing after new program is saved

package.json
This is in response to an issue causing CI builds to fail in Jenkins, introduced by https://github.com/edx/configuration/pull/2602. The failures are due to the fact that gulp and its dependencies weren't included in Programs' production node dependencies.
@clintonb @jibsheet please review. I've manually started [a build](http://jenkins.edx.org:8080/job/ansible-provision-continuous-integration/21146/) pointing at this branch to verify that these changes fix the problem.
=> Reorganize dependencies to allow gulp tasks to be run during production deployments

programs/apps/api/serializers.py, programs/apps/api/v1/tests/test_views.py, programs/apps/programs/fixtures/sample_data.json, programs/apps/programs/migrations/0006_auto_20160104_1920.py, programs/apps/programs/models.py, programs/apps/programs/tests/test_models.py
Avoids use of Field.null on string-based fields, as suggested by [Django's documentation](https://docs.djangoproject.com/en/1.9/ref/models/fields/#null). Enforces uniqueness of non-empty marketing slugs in code instead of at the database level. ECOM-2918.
The included migration will replace any NULL values in the affected fields with the empty string. The migration will lock affected tables when it is run, but we should be able to tolerate this. Presently, users only interact with the Programs service via the Programs API. The LMS caches the result of successful calls to the Programs API and is robust to failed calls. Worst case, a handful of users may not see XSeries messaging on their dashboard for a brief period while the migration is applied.
@jimabramson please review when you're …
=> Correct handling of optional, empty fields

programs/static/js/utils/auth_utils.js
@rlucioni @AlasdairSwan FYI, yet another little fix.
This avoids 'Studio is having trouble saving your work' from popping up after a 401 that will be retried using the auth_utils.  This is not a jQuery API but something that's already implemented in Studio, see https://github.com/edx/edx-platform/blob/master/cms/static/coffee/src/main.coffee#L22
There is a theoretical corner case in which this approach may cause a legitimate error NOT to trigger the popup, however I haven't been able to create such a situation on purpose, and I'm frankly not too worried about it.
=> suppress Studio’s error popup on the initial 401

programs/static/js/models/pagination_model.js
Fixes an issue I encountered on the sandbox, and might otherwise have bit on prod.  If the apiConfig is accessed at load time (while resolving dependencies) its default values may not yet have been overwritten by the app.
@AlasdairSwan @rlucioni FYI.
=> wait until initialize() to read from apiConfig.

programs/static/js/collections/course_runs_collection.js
@AlasdairSwan @rlucioni I'm not sure how this slipped through, but the query filter we've been using was incorrect.  Please review.
=> filter course runs by org key, not display_name

programs/static/js/models/program_model.js, programs/static/js/test/specs/program_creator_spec.js, programs/static/js/test/specs/program_details_spec.js
Fixes an issue preventing existing programs with long but technically legal names from being saved.
@jimabramson @AlasdairSwan
=> Sync up JS app with Django models to allow longer program names

programs/apps/programs/management/commands/sync_orgs.py, programs/apps/programs/tests/test_sync_orgs.py, requirements/base.txt
Takes advantage of the client credentials grant to get an access token when one isn't provided. ECOM-3349.
@bderusha please review.
=> Make access token optional when running sync_orgs command

requirements/base.txt
The opaque-keys package is available on PyPI. FYI @schenedx @jimabramson @clintonb
=> Install opaque-keys from PyPI

programs/apps/programs/migrations/0007_auto_20160318_1859.py, programs/apps/programs/models.py
The original size does not fit the dimensions of the program cards well.
Tweak the sizes of the banner images so the program cards looks better
=> ECOM-3198 Add a new set of sizes to the banner image for display

.gitignore, Makefile
This will allow test results to be more easily consumed by:
* CI infrastructure
* Developers who want to understand results
* Logging infrastructure we use wherein we can roll together test results across repos
=> Capture acceptance test results in an xunit.xml file

requirements/base.txt
ECOM-4248.
@clintonb @schenedx, FYI. 1.8.12 was released on April 1 and contains bug fixes. [Release notes](https://docs.djangoproject.com/es/1.9/releases/1.8.12/).
=> Upgrade Django to 1.8.12

requirements/base.txt
This version of the package stores the token_type in the User.extra_data.
ECOM-4263
=> Updated edx-auth-backends to 0.2.1

programs/apps/programs/management/commands/sync_orgs.py, programs/apps/programs/tests/test_sync_orgs.py
In case their display name has changed, orgs should initially be looked up by key. The display name can be updated separately.
@schenedx or @jimabramson, could I get a review from one of you? @jibsheet FYI, this will fix the error we observed.
=> Fix overly specific get_or_create preventing org sync

Makefile, programs/apps/api/serializers.py, programs/apps/api/v1/tests/test_views.py, programs/apps/programs/admin.py, programs/apps/programs/migrations/0010_programdefault.py, programs/apps/programs/models.py, programs/apps/programs/tests/factories.py, programs/apps/programs/tests/helpers.py, programs/apps/programs/tests/test_models.py, programs/settings/base.py, requirements/base.txt
@rlucioni Please review
Tested using django admin:
- Created a default program banner image within the DefaultProgramValue object
-- Made sure the API returned the default image
-- Made sure when a program already have the banner image defined, the program defined banner image urls are returned
- Try to add a new DefaultProgramValue object and made sure the error is handled gracefully in django admin
=> ECOM-3237 Default Program Images for Programs Listing Page

programs/apps/programs/fields.py, programs/apps/programs/tests/test_fields.py
The line in PR https://github.com/edx/programs/pull/128/files#diff-b4b27d9e5b70b25e71fa7e0fd5762a21R118 is problematic if we use S3BotoStorageFile implementation of the Django Storage API. That implementation do not have a "created_time". Instead, it has the "modified_time" property for this purpose.
This fixes that
@rlucioni Please review
=> ECOM-4403 fix the bug with clean stale images

programs/apps/programs/migrations/0011_auto_20160510_1524.py, programs/apps/programs/models.py, programs/apps/programs/tests/test_sync_orgs.py
@rlucioni Please review
@AlasdairSwan FYI
Tested locally:
- Made sure with a dupe long name in the LMS organization data, the sync command fails before the change
- After the change, make sure the sync command succeeds
=> ECOM-4309 update the Organization model to remove the display_name unique constraint

programs/settings/base.py, requirements/base.txt
I was going to upgrade to 0.11.1 but then realized this project doesn't actually use Waffle.
@edx/ecommerce
=> Remove django-waffle (unused)

programs/apps/api/authentication.py, programs/apps/api/tests/test_authentication.py, programs/apps/api/v1/views.py
Even with MySQL set to use the READ COMMITTED isolation level, get_or_create during JWT authentication sometimes raises an IntegrityError and the user in question fails to appear in a subsequent get() call. These changes address this issue by disabling atomic requests for the programs API and introducing more robust retry logic meant to prevent IntegrityErrors from causing authenticated requests to fail. ECOM-4506.
@cpennington please review. @mikedikan @schenedx FYI.
=> Make user creation during JWT authentication more robust

package.json
This reverts commit 8e18bca1dee2791c5408616a168ff84960d003bc. node-sass@3.4.2 works with the latest node LTS (v4.4.x), but not the latest, unstable node (v6.x.x). Programs may be installed in places where the node version is unpinned and defaults to 6.x.x.
@efischer19
=> Revert "Fix CSS compilation"

programs/settings/production.py
@e0d @maxrothman @clintonb 
This was removed in https://github.com/edx/programs/commit/ec2a6cd8a01bff561e8d0b61988be68c8ea1d949#diff-2ca989f014687f3223a751f4dbc2756eL34.
=> Unpack media storage settings when applying config overrides

Makefile, programs/settings/base.py, programs/settings/production.py, programs/settings/test.py, requirements/base.txt
We no longer use this tool. Counterpart to https://github.com/edx/configuration/pull/3267.
@schenedx @mikedikan please review.
=> Remove django-compressor

programs/apps/programs/constants.py, programs/apps/programs/migrations/0013_auto_20160725_2147.py
Ultimately, these will be replaced by a proper ProgramCategory model. In the meantime, correcting the casing here does away with the need to force consumers of this API to parse and hardcode references to these categories. Django doesn't enforce choices on a database level; the migration exists to appease Django 1.8's migrations framework. Part of ECOM-5018.
Since we intend to roll this into the catalog, I realize that we should generally avoid making changes to this code. However, I think the benefits of doing this make this case an exception. I'm going to create corresponding PRs for Studio and the LMS.
@mikedikan @schenedx please review. @bderusha @clintonb FYI.
=> Case category constants for display

requirements/optional.txt
This update specifically resolves a bunch of "data collector is not contactable" errors spamming our logs due to the agent keeping connections open too long and erroring when they are closed on it.
FYI @edx/ecommerce
=> Update new relic agent to v2.70

.travis.yml, .travis/run_coverage.sh, .travis/run_tests.sh, docker-compose-travis.yml
This is not 100% yet - it doesn't pass down the token for codecov, I need to find where we set it and pass it into the docker container.
There are about 7 ways to skin the container build/run cat, but I think this is simple if a bit inelegant.
I'll rename the shell script, and Ed and I discussed possibly generating it from the travis.yml runtime instead.  
Just wanted to get any initial thoughts/concerns from @e0d @clintonb @rlucioni
=> Use a 16.04 docker image to test
